create table CRAWLER_LOG (
 CHANNEL_ID  BIGINT NOT NULL,
 URL         VARCHAR(512) NOT NULL,
 CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY (CHANNEL_ID,URL)
);

create table TWAP_PUBLIC_CRAWL_RESOURCE (
   RES_ID              BIGINT not null generated by default as identity (start with 1,increment by 1),
   CHANNEL_ID          BIGINT,
   RES_TITLE           VARCHAR(512),
   RES_LINK            VARCHAR(512),
   RES_CONTENT         VARCHAR(4000),
   RES_IMG_PATH_SET    VARCHAR(4000),
   RES_IMAGES          CLOB,
   RES_TEXT            CLOB,
   RES_STATUS          CHAR(1) default '0',/*0:Œ¥…Û∫À 1:“—…Û∫À*/
   CREATE_TIME         DATE  default current_date,
   constraint PK_TWAP_PUBLIC_CRAWL_RESOURCE primary key (RES_ID)
)
;